version: "2.1"
services:
  frontend:
    build: iGEM_Scraper_React
    image: frontend-container:v1
    container_name: frontend-container
    environment:
      REACT_APP_APIURL: "http://127.0.0.1:5233/"
    ports:
      - 3300:3000/tcp
  backend:
    build: iGEM_Scraper_Django
    image: backend-container:v1
    container_name: backend-container
    environment:
      SECRET_KEY: secretkey1234*
    ports:
      - 5233:8000/tcp
